version: '3'
services:
  receipt-scanner:
    build:
      context: .
      dockerfile: DockerFile
    container_name: receipt-scanner
    ports:
      - '5000:5000'

    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - DATABASE_USERNAME=postgress
      - DATABASE_PASSWORD=postgres
    ports:
      - '5433:5433'
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
